"""init

Revision ID: 147614e3fb8a
Revises: 5b9d8d77b1ae
Create Date: 2025-10-30 09:00:01.860071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147614e3fb8a'
down_revision: Union[str, Sequence[str], None] = '5b9d8d77b1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SubToDo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['ToDo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SubToDo')
    # ### end Alembic commands ###
