"""init

Revision ID: 73e1e5964752
Revises: 518a23a25780
Create Date: 2025-10-28 09:21:04.871599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e1e5964752'
down_revision: Union[str, Sequence[str], None] = '518a23a25780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ToDo', 'date',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ToDo', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
